version: '3.8'
name: little-blue-book
services:
  mysql:
    container_name: little-blue-book-mysql
    image: mysql:8.0.35
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13306:3306"
  redis:
    container_name: little-blue-book-redis
    image: 'redis:7'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
  mongo:
    container_name: little-blue-book-mongo
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - '27017:27017'