// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ChongYanOvO/little-blue-book/core"
	"github.com/ChongYanOvO/little-blue-book/core/bootstrap"
	"github.com/ChongYanOvO/little-blue-book/internal/handler"
	"github.com/ChongYanOvO/little-blue-book/internal/repository"
	"github.com/ChongYanOvO/little-blue-book/internal/repository/cache"
	"github.com/ChongYanOvO/little-blue-book/internal/repository/dao"
	"github.com/ChongYanOvO/little-blue-book/internal/service"
	"github.com/ChongYanOvO/little-blue-book/internal/service/sms"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitApp() (core.Application, error) {
	viper := bootstrap.NewViper()
	config := bootstrap.NewConfig(viper)
	logger := bootstrap.NewZap(config)
	db := bootstrap.NewMysql(config, logger)
	cmdable := bootstrap.NewRedis(config)
	v := bootstrap.NewMiddleware(logger)
	userDao := dao.NewUserDao(db, logger)
	userCache := cache.NewRedisUserCache(cmdable, logger)
	userRepository := repository.NewUserRepository(userDao, userCache, logger)
	userService := service.NewUserService(userRepository, logger)
	codeCache := cache.NewCodeCache(cmdable, logger)
	codeRepository := repository.NewCodeRepository(codeCache, logger)
	smsService := sms.NewMemoryService(logger)
	codeService := service.NewCodeService(codeRepository, smsService, logger)
	userHandler := handler.NewUserHandler(userService, codeService, logger)
	engine := bootstrap.NewServer(v, userHandler)
	application := core.NewApplication(config, db, cmdable, logger, engine)
	return application, nil
}

func InitConfig() (*bootstrap.Config, error) {
	viper := bootstrap.NewViper()
	config := bootstrap.NewConfig(viper)
	return config, nil
}

// wire.go:

var BaseProvider = wire.NewSet(bootstrap.NewViper, bootstrap.NewConfig, bootstrap.NewMysql, bootstrap.NewRedis, bootstrap.NewZap, bootstrap.NewMiddleware, bootstrap.NewServer, core.NewApplication)

var UserProvider = wire.NewSet(cache.NewCodeCache, cache.NewRedisUserCache, dao.NewUserDao, repository.NewCodeRepository, repository.NewUserRepository, sms.NewMemoryService, service.NewCodeService, service.NewUserService, handler.NewUserHandler)
